"""Turn a recorded run into a runnable test script.

The agent's value only lands if the run leaves something behind that a QA
engineer can commit. Three targets are supported: pytest + Appium-Python-Client,
WebdriverIO (JS), and a plain Gherkin feature file.
"""

import datetime
import json
import re
from typing import Any, Dict, List, Optional

MOBILE_FORMATS = ("pytest", "webdriverio", "gherkin")
WEB_FORMATS = ("playwright-python", "playwright-ts", "gherkin")
FORMATS = ("pytest", "webdriverio", "gherkin", "playwright-python", "playwright-ts")


def formats_for(run: Dict[str, Any]) -> List[str]:
    """A run recorded against a browser exports to Playwright, not Appium."""
    return list(WEB_FORMATS if is_web_run(run) else MOBILE_FORMATS)


def is_web_run(run: Dict[str, Any]) -> bool:
    return (run.get("platform") or "").lower() == "web"


def _slug(text: str, fallback: str = "test_scenario") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", (text or "").lower()).strip("_")
    return slug[:60] or fallback


def _comment(text: Optional[str]) -> str:
    """Collapse a reason to a single safe comment line."""
    return re.sub(r"\s+", " ", (text or "")).strip()[:160]


def _py_str(value: Optional[str]) -> str:
    return json.dumps(value if value is not None else "", ensure_ascii=False)


def _selector(step: Dict[str, Any]) -> Dict[str, Optional[str]]:
    """Best available locator for a step, preferring stable identifiers."""
    element = step.get("element") or {}
    return {
        "id": element.get("id"),
        "text": element.get("text"),
        "desc": element.get("content-desc"),
        "xpath": element.get("xpath"),
        "label": step.get("target") or element.get("text") or element.get("id") or "element",
    }


def _successful_steps(run: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [s for s in run.get("steps", []) if s.get("status") == "passed"]


# --------------------------------------------------------------------------- #
# pytest + Appium-Python-Client
# --------------------------------------------------------------------------- #

def to_pytest(run: Dict[str, Any]) -> str:
    platform = (run.get("platform") or "Android").lower()
    is_android = platform == "android"
    automation = "UiAutomator2" if is_android else "XCUITest"
    options_cls = "UiAutomator2Options" if is_android else "XCUITestOptions"
    options_import = (
        "from appium.options.android import UiAutomator2Options"
        if is_android
        else "from appium.options.ios import XCUITestOptions"
    )
    app_cap = (
        f'    options.app_package = {_py_str(run.get("app_id"))}\n' if is_android and run.get("app_id")
        else f'    options.bundle_id = {_py_str(run.get("app_id"))}\n' if run.get("app_id")
        else ""
    )

    lines = [
        '"""',
        f'Generated by QAi on {datetime.datetime.now():%Y-%m-%d %H:%M}.',
        f'Scenario: {run.get("title", "Untitled")}',
        f'Goal: {run.get("goal", "")}',
        "",
        "Run with:  pytest -v " + _slug(run.get("title", ""), "test_scenario") + ".py",
        '"""',
        "",
        "import pytest",
        "from appium import webdriver",
        "from appium.webdriver.common.appiumby import AppiumBy",
        "from selenium.webdriver.support.ui import WebDriverWait",
        "from selenium.webdriver.support import expected_conditions as EC",
        options_import,
        "",
        "APPIUM_SERVER = \"http://localhost:4723\"",
        "TIMEOUT = 15",
        "",
        "",
        "@pytest.fixture(scope=\"module\")",
        "def driver():",
        f"    options = {options_cls}()",
        f'    options.platform_name = {_py_str(run.get("platform") or "Android")}',
        f'    options.automation_name = "{automation}"',
        f'    options.udid = {_py_str(run.get("device_udid"))}',
        "    options.no_reset = True",
    ]
    if app_cap:
        lines.append(app_cap.rstrip("\n"))
    lines += [
        "    driver = webdriver.Remote(APPIUM_SERVER, options=options)",
        "    yield driver",
        "    driver.quit()",
        "",
        "",
        "def find(driver, by, value):",
        "    return WebDriverWait(driver, TIMEOUT).until(",
        "        EC.presence_of_element_located((by, value))",
        "    )",
        "",
        "",
        f'def test_{_slug(run.get("title", ""))}(driver):',
    ]

    body: List[str] = []
    for step in _successful_steps(run):
        action = step.get("action")
        sel = _selector(step)
        comment = _comment(step.get("reason") or step.get("message"))
        if comment:
            body.append(f"    # {comment}")

        by, value = _pick_locator(sel)
        if action == "click":
            body.append(f"    find(driver, {by}, {_py_str(value)}).click()")
        elif action == "type":
            body.append(f"    field = find(driver, {by}, {_py_str(value)})")
            body.append("    field.clear()")
            body.append(f'    field.send_keys({_py_str(step.get("value"))})')
        elif action == "clear":
            body.append(f"    find(driver, {by}, {_py_str(value)}).clear()")
        elif action == "assert_visible":
            message = "Expected " + str(sel["label"]) + " to be visible"
            body.append(f"    assert find(driver, {by}, {_py_str(value)}).is_displayed(), \\")
            body.append("        " + _py_str(message))
        elif action == "assert_text":
            needle = step.get("value") or ""
            body.append(f"    expected = {_py_str(needle)}")
            body.append("    assert expected in driver.page_source, \\")
            body.append('        f"Expected {expected!r} to be on screen"')
        elif action == "scroll":
            direction = step.get("value") or "down"
            body.append(f'    driver.execute_script("mobile: scrollGesture", {{')
            body.append('        "left": 100, "top": 300, "width": 800, "height": 1200,')
            body.append(f'        "direction": {_py_str(direction)}, "percent": 0.75,')
            body.append("    })")
        elif action == "key":
            key = step.get("value") or step.get("target") or "back"
            if is_android:
                body.append(f'    driver.press_keycode({_ANDROID_KEYCODES.get(key, 4)})  # {key}')
            else:
                body.append(f'    driver.execute_script("mobile: pressButton", {{"name": {_py_str(key)}}})')
        elif action == "wait":
            body.append(f'    import time; time.sleep({step.get("value") or 1})')
        body.append("")

    lines += body or ["    pytest.skip(\"No successful steps were recorded for this run.\")"]
    return "\n".join(lines).rstrip() + "\n"


_ANDROID_KEYCODES = {"home": 3, "back": 4, "menu": 82, "recents": 187, "enter": 66}


def _pick_locator(sel: Dict[str, Optional[str]]):
    if sel.get("id"):
        return "AppiumBy.ID", sel["id"]
    if sel.get("desc"):
        return "AppiumBy.ACCESSIBILITY_ID", sel["desc"]
    if sel.get("text"):
        return "AppiumBy.XPATH", f'//*[@text={json.dumps(sel["text"], ensure_ascii=False)}]'
    return "AppiumBy.XPATH", sel.get("xpath") or "//*"


# --------------------------------------------------------------------------- #
# WebdriverIO
# --------------------------------------------------------------------------- #

def _wdio_selector(sel: Dict[str, Optional[str]]) -> str:
    if sel.get("id"):
        return json.dumps(f'id={sel["id"]}', ensure_ascii=False)
    if sel.get("desc"):
        return json.dumps(f'~{sel["desc"]}', ensure_ascii=False)
    if sel.get("text"):
        return json.dumps(f'//*[@text="{sel["text"]}"]', ensure_ascii=False)
    return json.dumps(sel.get("xpath") or "//*", ensure_ascii=False)


def to_webdriverio(run: Dict[str, Any]) -> str:
    lines = [
        "/**",
        f' * Generated by QAi on {datetime.datetime.now():%Y-%m-%d %H:%M}.',
        f' * Scenario: {run.get("title", "Untitled")}',
        f' * Goal: {run.get("goal", "")}',
        " */",
        "",
        f'describe({json.dumps(run.get("title", "Generated scenario"), ensure_ascii=False)}, () => {{',
        f'  it({json.dumps(run.get("goal", "runs the recorded scenario")[:120], ensure_ascii=False)}, async () => {{',
    ]

    body: List[str] = []
    for step in _successful_steps(run):
        action = step.get("action")
        sel = _selector(step)
        selector = _wdio_selector(sel)
        reason = _comment(step.get("reason"))
        if reason:
            body.append(f"    // {reason}")

        if action == "click":
            body.append(f"    await $({selector}).click();")
        elif action == "type":
            body.append(f"    await $({selector}).clearValue();")
            body.append(f'    await $({selector}).setValue({json.dumps(step.get("value") or "", ensure_ascii=False)});')
        elif action == "clear":
            body.append(f"    await $({selector}).clearValue();")
        elif action == "assert_visible":
            body.append(f"    await expect($({selector})).toBeDisplayed();")
        elif action == "assert_text":
            needle = json.dumps(step.get("value") or "", ensure_ascii=False)
            body.append(f"    await expect(await driver.getPageSource()).toContain({needle});")
        elif action == "scroll":
            direction = step.get("value") or "down"
            body.append(f'    await driver.execute("mobile: scrollGesture", {{')
            body.append("      left: 100, top: 300, width: 800, height: 1200,")
            body.append(f'      direction: {json.dumps(direction)}, percent: 0.75,')
            body.append("    });")
        elif action == "key":
            key = step.get("value") or step.get("target") or "back"
            body.append(f"    await driver.pressKeyCode({_ANDROID_KEYCODES.get(key, 4)}); // {key}")
        elif action == "wait":
            body.append(f'    await browser.pause({int(float(step.get("value") or 1) * 1000)});')

    lines += body or ["    // No successful steps were recorded for this run."]
    lines += ["  });", "});", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Gherkin
# --------------------------------------------------------------------------- #

_GHERKIN_VERBS = {
    "click": "I tap on",
    "type": "I enter text into",
    "clear": "I clear",
    "scroll": "I scroll",
    "key": "I press the",
    "wait": "I wait",
}


def to_gherkin(run: Dict[str, Any]) -> str:
    lines = [
        f'Feature: {run.get("title", "Generated scenario")}',
        f'  {run.get("goal", "")}',
        "",
        f'  # Generated by QAi on {datetime.datetime.now():%Y-%m-%d %H:%M}',
        f'  Scenario: {run.get("title", "Recorded scenario")}',
        f'    Given the app is open on a {run.get("platform", "mobile")} device',
    ]

    first = True
    for step in _successful_steps(run):
        keyword = "When" if first else "And"
        action = step.get("action")
        sel = _selector(step)
        label = sel["label"]

        if action in ("assert_visible", "assert_text"):
            expected = step.get("value") or label
            lines.append(f'    Then I should see "{expected}"')
            continue

        if action == "type":
            lines.append(f'    {keyword} I enter "{step.get("value") or ""}" into "{label}"')
        elif action == "key":
            lines.append(f'    {keyword} I press the "{step.get("value") or label}" key')
        elif action == "scroll":
            lines.append(f'    {keyword} I scroll {step.get("value") or "down"}')
        elif action == "wait":
            lines.append(f'    {keyword} I wait {step.get("value") or 1} seconds')
        else:
            verb = _GHERKIN_VERBS.get(action, f"I {action}")
            lines.append(f'    {keyword} {verb} "{label}"')
        first = False

    if first:
        lines.append("    # No successful steps were recorded for this run.")

    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Playwright — the web target's native output
# --------------------------------------------------------------------------- #

def _pw_selector(step: Dict[str, Any]) -> str:
    element = step.get("element") or {}
    # The web extractor already picked the most stable locator it could find and
    # stored it as the element's selector.
    return element.get("xpath") or "body"


def to_playwright_python(run: Dict[str, Any]) -> str:
    start_url = run.get("app_id") or run.get("device_name") or "about:blank"
    lines = [
        '"""',
        f"Generated by QAi on {datetime.datetime.now():%Y-%m-%d %H:%M}.",
        f'Scenario: {run.get("title", "Untitled")}',
        f'Goal: {run.get("goal", "")}',
        "",
        "Run with:  pytest -v " + _slug(run.get("title", ""), "test_scenario") + ".py",
        '"""',
        "",
        "import pytest",
        "from playwright.sync_api import Page, expect",
        "",
        f"START_URL = {_py_str(start_url)}",
        "",
        "",
        f'def test_{_slug(run.get("title", ""))}(page: Page):',
        "    page.goto(START_URL)",
    ]

    body: List[str] = []
    for step in _successful_steps(run):
        action = step.get("action")
        selector = _pw_selector(step)
        comment = _comment(step.get("reason") or step.get("message"))
        if comment:
            body.append(f"    # {comment}")

        if action == "click":
            body.append(f"    page.locator({_py_str(selector)}).click()")
        elif action == "type":
            body.append(f'    page.locator({_py_str(selector)}).fill({_py_str(step.get("value"))})')
        elif action == "clear":
            body.append(f'    page.locator({_py_str(selector)}).fill("")')
        elif action == "assert_visible":
            body.append(f"    expect(page.locator({_py_str(selector)})).to_be_visible()")
        elif action == "assert_text":
            body.append(f'    expect(page.get_by_text({_py_str(step.get("value"))}).first).to_be_visible()')
        elif action == "scroll":
            direction = step.get("value") or "down"
            sign = "" if direction == "down" else "-"
            body.append(f'    page.mouse.wheel(0, {sign}600)  # {direction}')
        elif action == "key":
            key = (step.get("value") or "back").lower()
            if key == "back":
                body.append("    page.go_back()")
            elif key == "forward":
                body.append("    page.go_forward()")
            else:
                body.append(f'    page.keyboard.press({_py_str(key.title())})')
        elif action == "wait":
            body.append(f'    page.wait_for_timeout({int(float(step.get("value") or 1) * 1000)})')
        body.append("")

    lines += body or ['    pytest.skip("No successful steps were recorded for this run.")']
    return "\n".join(lines).rstrip() + "\n"


def to_playwright_ts(run: Dict[str, Any]) -> str:
    start_url = run.get("app_id") or run.get("device_name") or "about:blank"
    lines = [
        "/**",
        f" * Generated by QAi on {datetime.datetime.now():%Y-%m-%d %H:%M}.",
        f' * Scenario: {run.get("title", "Untitled")}',
        f' * Goal: {run.get("goal", "")}',
        " */",
        "",
        "import { test, expect } from '@playwright/test';",
        "",
        f"const START_URL = {json.dumps(start_url)};",
        "",
        f'test({json.dumps(run.get("title", "Generated scenario"), ensure_ascii=False)}, async ({{ page }}) => {{',
        "  await page.goto(START_URL);",
    ]

    body: List[str] = []
    for step in _successful_steps(run):
        action = step.get("action")
        selector = json.dumps(_pw_selector(step), ensure_ascii=False)
        comment = _comment(step.get("reason"))
        if comment:
            body.append(f"  // {comment}")

        if action == "click":
            body.append(f"  await page.locator({selector}).click();")
        elif action == "type":
            body.append(f'  await page.locator({selector}).fill({json.dumps(step.get("value") or "", ensure_ascii=False)});')
        elif action == "clear":
            body.append(f'  await page.locator({selector}).fill("");')
        elif action == "assert_visible":
            body.append(f"  await expect(page.locator({selector})).toBeVisible();")
        elif action == "assert_text":
            needle = json.dumps(step.get("value") or "", ensure_ascii=False)
            body.append(f"  await expect(page.getByText({needle}).first()).toBeVisible();")
        elif action == "scroll":
            direction = step.get("value") or "down"
            sign = "" if direction == "down" else "-"
            body.append(f"  await page.mouse.wheel(0, {sign}600); // {direction}")
        elif action == "key":
            key = (step.get("value") or "back").lower()
            if key == "back":
                body.append("  await page.goBack();")
            elif key == "forward":
                body.append("  await page.goForward();")
            else:
                body.append(f"  await page.keyboard.press({json.dumps(key.title())});")
        elif action == "wait":
            body.append(f'  await page.waitForTimeout({int(float(step.get("value") or 1) * 1000)});')

    lines += body or ["  // No successful steps were recorded for this run."]
    lines += ["});", ""]
    return "\n".join(lines)


EXTENSIONS = {
    "pytest": "py", "webdriverio": "js", "gherkin": "feature",
    "playwright-python": "py", "playwright-ts": "spec.ts",
}

_GENERATORS = {
    "pytest": to_pytest,
    "webdriverio": to_webdriverio,
    "gherkin": to_gherkin,
    "playwright-python": to_playwright_python,
    "playwright-ts": to_playwright_ts,
}


def export(run: Dict[str, Any], fmt: str) -> Dict[str, str]:
    fmt = (fmt or "").lower() or ("playwright-python" if is_web_run(run) else "pytest")
    if fmt not in FORMATS:
        raise ValueError(f"Unsupported export format '{fmt}'. Use one of: {', '.join(FORMATS)}")

    prefix = "test_" if fmt in ("pytest", "playwright-python") else ""
    return {
        "format": fmt,
        "filename": f'{prefix}{_slug(run.get("title", ""))}.{EXTENSIONS[fmt]}',
        "content": _GENERATORS[fmt](run),
    }
